-- ============================================================================
-- integration_test_disposable.sql
-- ============================================================================
-- PREPARED ONLY — DO NOT EXECUTE until BOTH approvals are given:
--   A) Framework migrations already applied and verified
--   B) Explicit second approval for disposable CREATE/DROP testing
--
-- Rules
--   * Uses ONLY schema partition_scheduler_test (synthetic)
--   * Never references existing business tables from the prod-copy
--   * No CASCADE against application schemas
--   * Cleanup targets ONLY objects created here
--   * partitioning_job_table must not be auto-filled with production tables
-- ============================================================================


-- Guard (same session approval marker used by migrations, plus a second marker):
--   CREATE TEMP TABLE _partition_realtime_migration_approved AS
--   SELECT now() AS approved_at, current_database() AS approved_database;
--   CREATE TEMP TABLE _partition_scheduler_destructive_test_approved AS
--   SELECT now() AS approved_at;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = '_partition_scheduler_destructive_test_approved'
          AND n.nspname LIKE 'pg_temp%' AND c.relkind = 'r'
    ) THEN
        RAISE EXCEPTION
            'Refusing disposable integration test DDL: create TEMP TABLE '
            '_partition_scheduler_destructive_test_approved after explicit approval.';
    END IF;

    IF to_regnamespace('partition_scheduler_test') IS NOT NULL THEN
        RAISE EXCEPTION
            'Schema partition_scheduler_test already exists — refusing to reuse/overwrite. '
            'Choose a new unique name or drop ONLY that disposable schema after approval.';
    END IF;
END
$$;


BEGIN;

CREATE SCHEMA partition_scheduler_test;

-- Minimal disposable partitioned parent for CREATE/DROP worker smoke tests.
-- Adjust partition strategy only if create_any_table_partition requires a specific shape;
-- verify against imported worker definition before enabling.
CREATE TABLE partition_scheduler_test.synth_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    event_time  timestamp without time zone NOT NULL,
    payload     text
) PARTITION BY RANGE (event_time);

COMMENT ON TABLE partition_scheduler_test.synth_events IS
    'DISPOSABLE scheduler integration target. Synthetic only. Not a business table.';

-- Example controlled CREATE job row (disabled by default until test start).
-- Insert ONLY after workers exist. Do not point at mubasher_oms business tables.
--
-- INSERT INTO mubasher_oms.partitioning_job_table (
--     job_name, is_enabled, table_schema, table_name, db_config_para,
--     frequency, next_run_time, partition_unit, partition_period,
--     is_create, create_drop_interval, job_schedule
-- ) VALUES (
--     'scheduler_test_create_synth_events',
--     false,
--     'partition_scheduler_test',
--     'synth_events',
--     '{}'::jsonb,
--     interval '1 day',
--     clock_timestamp()::timestamp without time zone + interval '30 seconds',
--     'day',
--     1,
--     true,
--     interval '7 days',
--     '0 0 2 * * *'
-- );

COMMIT;


-- ----------------------------------------------------------------------------
-- CLEANUP (run only after explicit approval; targets disposable objects only)
-- ----------------------------------------------------------------------------
-- DELETE FROM mubasher_oms.partitioning_job_table_log
--  WHERE job_id IN (
--      SELECT job_id FROM mubasher_oms.partitioning_job_table
--       WHERE table_schema = 'partition_scheduler_test'
--  );
-- DELETE FROM mubasher_oms.partitioning_job_table
--  WHERE table_schema = 'partition_scheduler_test';
-- DROP TABLE IF EXISTS partition_scheduler_test.synth_events;
-- DROP SCHEMA IF EXISTS partition_scheduler_test RESTRICT;
